joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: msl_robot_controller/cmd_vel

      deadman_buttons: [5]

      axis_mappings:
        twist-linear-x:
          axis: 1
          scale: 0.3
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 1.5
          offset: 0.0